# mini-lang justfile

# Show available commands
default:
    @just --list

# ---- Development ----

# Run main.go
@run:
    go run main.go

# Format using go fmt
@fmt:
    go fmt ./...

# Go vet
@vet:
    go vet ./...

# Run tests
@test:
    go test ./...
