# mini-lang justfile

set shell := ["nu", "-c"]

# Show available commands
default:
    @just --list

# ---- Development ----

# Run main.go
@run:
    go run main.go

# Run main.go in watch mode (nushell)
@dev:
    watch . --glob="**/*.go" {just run}

# Format using go fmt
@fmt:
    go fmt ./...

# Go vet
@vet:
    go vet ./...

# Run tests
@test:
    go test ./...
